config/routes.rb
Stolpersteine::Application.routes.draw do

  resources :locations
  resources :biographies

  get 'locations/:lat/:lng/(:radius)', to: 'locations#index'

  

end

app/models/biography.rb
class Biography < ActiveRecord::Base
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :biographies, dependent: :destroy

  # By default, use the GEOS implementation for spatial columns.
  self.rgeo_factory_generator = RGeo::Geos.factory_generator

  # But use a geographic implementation for the :lnglat column.
  GEOG_FACTORY ||= RGeo::Geographic.spherical_factory(:srid => 4326)
  set_rgeo_factory_for_column(:lnglat, GEOG_FACTORY)

  scope :nearby, lambda { |radius_in_km, lng, lat|
    point = GEOG_FACTORY.point(lng, lat)
    where("ST_DWithin(lnglat, ST_GeomFromText('#{point}'), #{radius_in_km.to_f*1000} )")
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/biographies_controller.rb
class BiographiesController < ApplicationController
  before_action :set_biography, only: [:show, :edit, :update, :destroy]

  # GET /biographies
  # GET /biographies.json
  def index
    @biographies = Biography.all
  end

  # GET /biographies/1
  # GET /biographies/1.json
  def show
    @biography = Biography.find(params[:id])
  end

  # GET /biographies/new
  def new
    @biography = Biography.new
  end

  # GET /biographies/1/edit
  def edit
  end

  # POST /biographies
  # POST /biographies.json
  def create
    @biography = Biography.new(biography_params)

    respond_to do |format|
      if @biography.save
        format.html { redirect_to @biography, notice: 'Biography was successfully created.' }
        format.json { render action: 'show', status: :created, location: @biography }
      else
        format.html { render action: 'new' }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biographies/1
  # PATCH/PUT /biographies/1.json
  def update
    respond_to do |format|
      if @biography.update(biography_params)
        format.html { redirect_to @biography, notice: 'Biography was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biographies/1
  # DELETE /biographies/1.json
  def destroy
    @biography.destroy
    respond_to do |format|
      format.html { redirect_to biographies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biography
      @biography = Biography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biography_params
      params.require(:biography).permit(:name, :geburtsname, :verlegedatum, :geburtstag, :geburtsort, :biografie, :occupation, :info)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /locations
  # GET /locations.json
  def index
    lat, lng = params[:lat], params[:lng]
    radius = params[:radius] || 1

    if lat and lng
      @locations = Location.nearby(radius, lng.to_f, lat.to_f)
    else
      @locations = Location.all
    end

    respond_to do |format|
      format.html
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  # Prevents using own json style
  def default_serializer_options
    { root: false }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:bezirk, :ortsteil, :adresse, :lnglat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biographies_helper.rb
module BiographiesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/biographies/_form.html.erb
<%= form_for(@biography) do |f| %>
  <% if @biography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biography.errors.count, "error") %> prohibited this biography from being saved:</h2>

      <ul>
      <% @biography.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :geburtsname %><br>
    <%= f.text_field :geburtsname %>
  </div>
  <div class="field">
    <%= f.label :verlegedatum %><br>
    <%= f.datetime_select :verlegedatum %>
  </div>
  <div class="field">
    <%= f.label :geburtstag %><br>
    <%= f.datetime_select :geburtstag %>
  </div>
  <div class="field">
    <%= f.label :geburtsort %><br>
    <%= f.text_field :geburtsort %>
  </div>
  <div class="field">
    <%= f.label :biografie %><br>
    <%= f.text_area :biografie %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biographies/edit.html.erb
<h1>Editing biography</h1>

<%= render 'form' %>

<%= link_to 'Show', @biography %> |
<%= link_to 'Back', biographies_path %>

app/views/biographies/index.html.erb
<h1>Listing biographies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adresse</th>
      <th>Geburtsname</th>
      <th>verlegedatum</th>
      <th>Geburtstag</th>
      <th>Geburtsort</th>
      <th>Biografie</th>
      <th>Info</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @biographies.each do |biography| %>
      <tr>
        <td><%= biography.name %></td>
        <td><%= biography.geburtsname %></td>
        <td><%= biography.verlegedatum %></td>
        <td><%= biography.geburtstag %></td>
        <td><%= biography.geburtsort %></td>
        <td><%= biography.biografie %></td>
        <td><%= biography.info %></td>
        <td><%= link_to 'Show', biography %></td>
        <td><%= link_to 'Edit', edit_biography_path(biography) %></td>
        <td><%= link_to 'Destroy', biography, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biography', new_biography_path %>

app/views/biographies/new.html.erb
<h1>New biography</h1>

<%= render 'form' %>

<%= link_to 'Back', biographies_path %>

app/views/biographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @biography.name %>
</p>

<p>
  <strong>Geburtsname:</strong>
  <%= @biography.geburtsname %>
</p>

<p>
  <strong>verlegedatum:</strong>
  <%= @biography.verlegedatum %>
</p>

<p>
  <strong>Geburtstag:</strong>
  <%= @biography.geburtstag %>
</p>

<p>
  <strong>Geburtsort:</strong>
  <%= @biography.geburtsort %>
</p>

<p>
  <strong>Biografie:</strong>
  <%= @biography.biografie %>
</p>

<p>
  <strong>Info:</strong>
  <%= @biography.info %>
</p>

<%= link_to 'Edit', edit_biography_path(@biography) %> |
<%= link_to 'Back', biographies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stolpersteine</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bezirk %><br>
    <%= f.text_field :bezirk %>
  </div>
  <div class="field">
    <%= f.label :ortsteil %><br>
    <%= f.text_field :ortsteil %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Bezirk</th>
      <th>Ortsteil</th>
      <th>Adresse</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.bezirk %></td>
        <td><%= location.ortsteil %></td>
        <td><%= location.adresse %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bezirk:</strong>
  <%= @location.bezirk %>
</p>

<p>
  <strong>Ortsteil:</strong>
  <%= @location.ortsteil %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @location.adresse %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>